---
apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: app
    image: gcr.io/kbot-385713/demo:v1.0.0
    ports:
    - containerPort: 8000
      name: http
    livenessProbe:
      httpGet:
        path: /ready
        port: 8000
      initialDelaySeconds: 0
      periodSeconds: 2
      failureThreshold: 3
      successThreshold: 1
    readinessProbe:
      httpGet:
        path: /ready
        port: 8000
      initialDelaySeconds: 0
      periodSeconds: 2
      failureThreshold: 3
      successThreshold: 1
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 256Mi
