---
apiVersion: v1
kind: Pod
metadata:
  name: app
  namespace: demo
spec:
  containers:
  - name: app
    image: gcr.io/kbot-385713/demo:v1.0.0
    ports:
    - containerPort: 8080
      name: http
    livenessProbe:
      httpGet:
        path: /
        port: 8000
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 3
